FROM node:lts as angular
WORKDIR /app
COPY package.json /app
RUN npm install --silent
COPY . .
RUN npm run build

FROM nginx:latest
VOLUME /var/cache/nginx
COPY --from=angular app/dist/BoxEven-Front /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf